import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
//------------------------------------------------------------------------------------------------
    //     roll function
    static int[] roll(int n) {
        int max = 6;
        int min = 1;
        int range = max - min + 1;
        int[] array = new int[n];
        for (int i = 0; i < array.length; i++) {
            array[i] = (int) (Math.random() * range) + min;
        }

        return array;
    }
//------------------------------------------------------------------------------------------------
    // contains Duplicates function
    static boolean containsDuplicates() {
        int max = 6;
        int min = 1;
        int range = max - min + 1;

        Set<Integer> s = new HashSet<Integer>();
        for (int i = 0; i < 10; i++) {
            int rand = (int) (Math.random() * range) + min;
            s.add(rand);
        }
        if (s.size() < 6) {
            // System.out.println(true);
            return true;
        } else {
            // System.out.println(false);
            return false;
        }
    }
//------------------------------------------------------------------------------------------------
    // avg function
static int arrayAvg(){
    int [] arr = {1,2,3,4,5,9};
    int sum = 0;
    int avg;
    for(int ele:arr){
        sum += ele;
    }
    avg = sum/arr.length;
    return avg;
}
//------------------------------------------------------------------------------------------------
//    2DArray funcation
static void multi (){
    int[][] array = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };
    int sum =0;
    for(int i=0;i<array.length;i++){
        for(int ele:array[i]){
            sum+= ele;
        }
        System.out.println(sum);
    }

}
//------------------------------------------------------------------------------------------------
    public static void main(String[] args) {
        System.out.println(Arrays.toString(roll(5)));
        System.out.print(containsDuplicates());
        arrayAvg();
        multi();

    }
}
