/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }


    @Test public void testRoll() {

        Library classUnderTest = new Library();
         int[] arr = classUnderTest.roll(5);
        assertEquals("This array should have random number between 1-6", 5,arr.length);

    }

    @Test public void testContainsDuplicates() {
        Library classUnderTest = new Library();
        assertTrue("It's should return 'true'", classUnderTest.containsDuplicates());
//        assertFalse("It's should return 'false'", classUnderTest.containsDuplicates());
    }
    @Test public void testArrayAvg() {
        Library classUnderTest = new Library();
        assertEquals(4,classUnderTest.arrayAvg());
    }
}
