/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {
        Restaurant shawermaRestaurent = new Restaurant("pizza Restaurent", "$$");
        Restaurant burgerResturant = new Restaurant("burgar Restaurent ", "$$$");
        Restaurant mansefResturant = new Restaurant("mansef Restaurent", "$$$$");
        Review shawermaReview = new Review("ahmad alsabbagh", 3, "not bad", shawermaRestaurent);
        Review shawermaReview2 = new Review("ahmad alsabbagh", 4, "very good",shawermaRestaurent);

        Review burgerReview = new Review(" abdullah ", 4, " nice one ",burgerResturant);
        shawermaRestaurent.addReview(shawermaReview);
        System.out.println(shawermaReview);
        System.out.println(shawermaRestaurent);

//        Shop shop =new Shop("M&M","goooood","$$$");
//        Review shopreview = new Review("Ahmad Alsabbagh",5,"nice",shop);
//
//
//        System.out.println(shopreview);
//
//        Theater theater = new Theater("taj Cinama","mad max");
//        Review theaterReview = new Review("Ahmad",5,"good move",theater);
//        System.out.println(theater);
//        System.out.println(theaterReview);
    }
}
