/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {
        Restaurant shwaermResturant = new Restaurant("pqzza resorant", "$$$");
        Restaurant burgerResturant = new Restaurant("burgar restarent ", "$$$");
        Restaurant mansefResturant = new Restaurant("mansef restarnent", "$$$$");
        Review shwaermReview = new Review("ahmad alsabbagh", 2, "very good",shwaermResturant);
        Review shwaermReview2 = new Review("ahmad alsabbagh", 4, "very good",shwaermResturant);

        Review burgerReview = new Review(" abdullah ", 4, " nice one ",burgerResturant);
        shwaermResturant.addReview(shwaermReview);
        shwaermResturant.addReview(shwaermReview2);
        System.out.println(shwaermResturant);

    }
}
