/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Shawerma",4,5);

        Review review = new Review("Very good restaurant","Ahmad Alsabbagh",4,restaurant.getName());

//        System.out.println(restaurant.toString());
        System.out.println(review.toString());

    }
}
