/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter1;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Objects;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().linter());
    }

    public String linter() {
        Path file = null;
        String str = "";
        try {
            file = Paths.get(Objects.requireNonNull(getClass().getClassLoader().getResource("gates.js")).toURI());

            String[] lines = Files.readAllLines(file).toArray(new String[0]);
            for (int i = 0; i < lines.length; i++) {
                int lineNum = i + 1;
                if (lines[i].contains("}")) {

                } else if (lines[i].contains("{")) {

                } else if (lines[i].contains("if")) {

                } else if (lines[i].contains("else")) {

                } else if (lines[i].contains(";")) {

                } else if (lines[i].isEmpty()) {

                } else {
                    str += "Line " + lineNum + ": Missing semicolon.\n";
                }

            }
        } catch (URISyntaxException | IOException ex) {
            ex.printStackTrace();
        }
        return str;
    }
}
