/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public  void testRestaurant(){
        Restaurant restaurant = new Restaurant("Shawerma",3,30);
        Restaurant restaurant1 = new Restaurant("Shawerma",7,50);

        assertEquals("Restaurant{name='Shawerma', numberOfStars=3, price=30$}",restaurant.toString());
        assertEquals("you should add number of stars between 0-5",restaurant1.toString());


    }
    @Test public  void testReview(){
        Restaurant restaurant = new Restaurant("Shawerma",3,30);

        Review review = new Review("Very good restaurant","Ahmad Alsabbagh",3,restaurant.getName());

        Review review1 = new Review("Very good restaurant","Ahmad Alsabbagh",8,restaurant.getName());

        assertEquals("Review{body='Very good restaurant', author='Ahmad Alsabbagh', numberOfStars=3,restaurantName =Shawerma}",review.toString());
        assertEquals("you should add number of stars between 0-5",review1.toString());


    }
}
