/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

public class LibraryTest {
    @Test
    public void testRestaurant() {

    }
}
