import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Path file = Paths.get("/home/sabbagh99/Desktop/ASAC/code-401/java-fundamentals/linter/src/main/resources/gates.js");
        try {
            String[] lines = Files.readAllLines(file).toArray(new String[0]);
            for(int i =0; i<lines.length;i++) {
                int lineNum = i + 1;
                if (lines[i].contains("}")) {

                }else if(lines[i].contains("{")) {

                }else if(lines[i].contains("if")){

                }else if (lines[i].contains("else")){

                }else if (lines[i].contains(";")){

                }else if (lines[i].isEmpty()){

                } else {
                    System.out.println("Line " + lineNum + ": Missing semicolon.");
                }

            }
        } catch (IOException ex){
            ex.printStackTrace();
        }
    }
}
